In [14]:
import numpy as np
import random

In [4]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones([2,3,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
np.random.randint(0,100,10)  #random int

array([96, 88, 44,  6, 89, 44, 61, 19, 75, 55])

In [27]:
np.random.uniform(0,1,10)   #random float

array([0.40713818, 0.96858268, 0.56626434, 0.48131836, 0.34666145,
       0.02763022, 0.87916475, 0.74975457, 0.58137742, 0.60927335])

In [42]:
np.linspace(0,1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
np.arange(0,1,.5)

array([0. , 0.5])

In [41]:
np.linspace(-1,1, num=5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [43]:
np.linspace(0,10, num=5)  

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
np.sin(np.arange(0,361,90))

array([ 0.        ,  0.89399666, -0.80115264, -0.17604595,  0.95891572])

In [51]:
np.sin(np.arange(0,361,90)* np.pi/180)

array([ 0.0000000e+00,  1.0000000e+00,  1.2246468e-16, -1.0000000e+00,
       -2.4492936e-16])

In [52]:
np.arange(0,361,90)

array([  0,  90, 180, 270, 360])

In [53]:
np.cos(np.arange(0,361,90)* np.pi/180)

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [54]:
np.cos(np.arange(0,361,90))

array([ 1.        , -0.44807362, -0.59846007,  0.98438195, -0.28369109])