In [18]:
import numpy as np

In [4]:
arr1=np.array([[1,2],[21,23]])

In [5]:
arr1*2

array([[ 2,  4],
       [42, 46]])

In [6]:
arr2=np.array([[1,2,3],[21,23,33]])

In [7]:
arr2+5

array([[ 6,  7,  8],
       [26, 28, 38]])

In [9]:
arr3=np.array([[1,2,3,6],[21,23,33,40]])
arr3-10

array([[-9, -8, -7, -4],
       [11, 13, 23, 30]])

In [10]:
arr4=np.array([[1,2,3,6,7],[21,23,33,40,15]])
arr4/2

array([[ 0.5,  1. ,  1.5,  3. ,  3.5],
       [10.5, 11.5, 16.5, 20. ,  7.5]])

In [17]:
arr5=np.array([[1,2,3,6,7,9],[21,23,33,40,15,20]])
np.sqrt(arr5)

array([[1.        , 1.41421356, 1.73205081, 2.44948974, 2.64575131,
        3.        ],
       [4.58257569, 4.79583152, 5.74456265, 6.32455532, 3.87298335,
        4.47213595]])

In [22]:
a1=np.array([[1,2],[21,23]])
a1

array([[ 1,  2],
       [21, 23]])

In [23]:
b1=np.array([[3,4],[33,34]])
b1

array([[ 3,  4],
       [33, 34]])

In [24]:
np.matmul(a1,b1)

array([[ 69,  72],
       [822, 866]])

In [43]:
a2=np.array([[1,2,3],[21,23,33],[3,6,9]])
a2

array([[ 1,  2,  3],
       [21, 23, 33],
       [ 3,  6,  9]])

In [44]:
b2=np.array([[3,4,6],[33,34,39],[1,5,7]])
b2

array([[ 3,  4,  6],
       [33, 34, 39],
       [ 1,  5,  7]])

In [48]:
np.dot(a2,b2)

array([[  72,   87,  105],
       [ 855, 1031, 1254],
       [ 216,  261,  315]])

In [46]:
b2.T

array([[ 3, 33,  1],
       [ 4, 34,  5],
       [ 6, 39,  7]])

In [50]:
np.dot(a2,b2.T)

array([[  29,  218,   32],
       [ 353, 2762,  367],
       [  87,  654,   96]])