In [2]:
import numpy as np
from numpy.random import randn

In [3]:
A= np.array([1,2,3,4])
B= np.array([100,200,300,400])

In [13]:
arr= randn(5,5)
arr

array([[-0.45049408,  0.42988766, -0.84047313,  0.73311641, -1.37413106],
       [ 0.03872854, -0.99143463,  0.42999965,  0.45423111, -0.4465583 ],
       [-2.4067741 , -0.71375115,  0.00718069, -0.20173072,  1.00756298],
       [-0.70226699,  0.87359261,  0.96105044, -0.29317756,  1.92964579],
       [-0.95609106,  0.8863629 ,  0.07447396,  0.1155309 , -0.52715576]])

In [14]:
m=0

In [15]:
sd=1

In [16]:
arr= randn(5,5)+m*sd
arr

array([[-1.59835622,  0.9007222 , -0.78964593,  1.77537473, -1.2632295 ],
       [-0.51239094,  0.1868367 , -1.3276592 ,  0.65652645, -1.88205732],
       [-0.26426494, -0.76100648, -1.0414904 ,  1.62758626, -0.5517654 ],
       [-0.65713436, -0.60954976, -0.34953356,  0.5931935 ,  0.17014813],
       [-1.0369926 , -0.3796762 ,  0.50677771,  1.67755808,  0.49338423]])

In [24]:
A=np.array([-2,5,4,-8,0])

In [25]:
print(np.sort(A)) #Ascending

[-8 -2  0  4  5]


In [26]:
print(np.sort(A)[::-1]) #Descending

[ 5  4  0 -2 -8]


In [27]:
names= np.array(['Bushra','Sara','Asma','Juhaina'])
np.unique(names)

array(['Asma', 'Bushra', 'Juhaina', 'Sara'], dtype='<U7')

In [28]:
np.in1d(['Sara','US','Asma'],names)  #check if there

array([ True, False,  True])