In [1]:
import numpy as np

In [4]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[2]     #3d element

2

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr1=np.array([[1,2,3,4],[21,23,25,33],[3,6,9,8],[4,12,9,10]])
arr1

array([[ 1,  2,  3,  4],
       [21, 23, 25, 33],
       [ 3,  6,  9,  8],
       [ 4, 12,  9, 10]])

In [15]:
arr1[1,0]   #row 2, column 1

21

In [34]:
arr1[:2,2:]     # first 2 rows, last 2 columns

array([[ 3,  4],
       [25, 33]])

In [35]:
arr[:3]   #first 3 elements

array([0, 1, 2])

In [36]:
arr2=np.array([[1,2,3],[21,23,25],[3,6,9]])
arr2

array([[ 1,  2,  3],
       [21, 23, 25],
       [ 3,  6,  9]])

In [46]:
arr2[:2,1:]      # first 2 rows, last 2 columns

array([[ 2,  3],
       [23, 25]])

In [47]:
arr2[:3,::2]    #first 3 rows, first and second columns

array([[ 1,  3],
       [21, 25],
       [ 3,  9]])

In [67]:
reshape1 = np.arange(0,9).reshape(3,3)
reshape1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
arr2.reshape(-1)   #2D to 1D

array([ 1,  2,  3, 21, 23, 25,  3,  6,  9])